import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { finalize } from 'rxjs';
import { Api, errorMessage } from '../core/api';

@Component({
  selector: 'app-accept-invitation', imports: [ReactiveFormsModule], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<main class="invite-page"><section class="invite-card"><a class="brand"><span>O</span> Ordivo</a>@if(done()){<div class="result"><div class="check">✓</div><h1>Acesso ativado</h1><p>Sua senha foi criada. Agora você já pode entrar no Ordivo.</p><a class="primary" href="/login">Ir para o login</a></div>}@else{<p class="eyebrow">CONVITE PARA A EQUIPE</p><h1>Crie sua senha</h1><p class="muted">Defina uma senha para concluir seu cadastro e acessar o espaço de trabalho.</p>@if(!token){<div class="alert">Este link de convite é inválido.</div>}@else{<form [formGroup]="form" (ngSubmit)="submit()"><label>Senha<input type="password" formControlName="password" autocomplete="new-password" placeholder="Mínimo de 8 caracteres"></label><label>Confirmar senha<input type="password" formControlName="confirmation" autocomplete="new-password" placeholder="Digite novamente"></label>@if(mismatch()){<div class="alert">As senhas não são iguais.</div>}@if(error()){<div class="alert">{{error()}}</div>}<button class="primary" [disabled]="form.invalid||mismatch()||loading()">{{loading()?'Ativando...':'Ativar minha conta'}} <span>→</span></button></form>}} </section></main>`,
  styles: [`:host{display:block}.invite-page{min-height:100vh;display:grid;place-items:center;padding:28px;background:#f4f6f1}.invite-card{width:min(440px,100%);padding:38px;background:#fff;border:1px solid #e1e7e0;border-radius:16px;box-shadow:0 18px 45px #173f3912}.brand{display:flex;align-items:center;gap:11px;margin-bottom:42px;font-size:21px;font-weight:800}.brand span{display:grid;place-items:center;width:34px;height:34px;border-radius:10px;background:#173f39;color:#e6ff72;font-family:Georgia,serif;font-style:italic}.eyebrow{font-size:10px;letter-spacing:.17em;font-weight:800;color:#64827d}h1{margin:8px 0;font-size:32px;letter-spacing:-.04em;color:#18322f}.muted,.result p{color:#74817f;line-height:1.55;font-size:13px;margin:0 0 28px}label{display:block;margin:17px 0 7px;font-size:12px;font-weight:800}input{display:block;width:100%;height:48px;margin-top:7px;padding:0 14px;border:1px solid #d9dfd9;border-radius:10px;font:inherit;outline:none}input:focus{border-color:#2d625a;box-shadow:0 0 0 3px #2d625a16}.primary{width:100%;margin-top:20px;justify-content:space-between}.alert{padding:11px 13px;margin-top:13px;border-radius:9px;background:#fff0ed;color:#a83c2d;font-size:12px}.result{text-align:center}.result .primary{display:flex}.check{display:grid;place-items:center;width:54px;height:54px;margin:0 auto 18px;border-radius:50%;background:#e5f2ed;color:#286658;font-size:25px}`]
})
export class AcceptInvitationComponent {
  private api=inject(Api); private fb=inject(FormBuilder); private route=inject(ActivatedRoute);
  token=this.route.snapshot.queryParamMap.get('token')??''; loading=signal(false); done=signal(false); error=signal('');
  form=this.fb.nonNullable.group({password:['',[Validators.required,Validators.minLength(8),Validators.maxLength(128)]],confirmation:['',Validators.required]});
  mismatch=()=>this.form.controls.confirmation.dirty&&this.form.controls.password.value!==this.form.controls.confirmation.value;
  submit(){if(!this.token||this.form.invalid||this.mismatch())return;this.loading.set(true);this.error.set('');this.api.post<boolean>('/api/auth/invitations/accept',{token:this.token,password:this.form.controls.password.value}).pipe(finalize(()=>this.loading.set(false))).subscribe({next:()=>this.done.set(true),error:error=>this.error.set(errorMessage(error))})}
}
