import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { CurrencyPipe, DatePipe } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { finalize } from 'rxjs';
import { Api, errorMessage } from '../core/api';
import { Subscription } from '../core/models';

interface CheckoutResult { checkoutId:string; checkoutUrl:string; }

@Component({selector:'app-tenant-billing',imports:[CurrencyPipe,DatePipe],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<div class="page-head"><div><p class="eyebrow">ASSINATURA</p><h1>Plano e cobrança</h1><p>Gerencie seu período gratuito e a assinatura do Ordivo.</p></div></div>
@if(message()){<div class="notice success">{{message()}}</div>}@if(error()){<div class="alert">{{error()}}</div>}
@if(item();as s){@if(s.status==='Trialing'){<div class="trial-banner" [class.urgent]="daysLeft()<=1"><div><b>{{daysLeft()>0?'Seu período gratuito está ativo':'Seu período gratuito terminou'}}</b><span>{{daysLeft()>1?'Você ainda tem '+daysLeft()+' dias para usar o Ordivo sem cobrança.':daysLeft()===1?'Seu trial termina amanhã. Cadastre o cartão para não perder o acesso.':'Assine agora para recuperar o acesso.'}}</span></div><strong>{{daysLeft()>0?daysLeft()+' dias':'Expirado'}}</strong></div>}
<section class="billing-grid"><article class="card current-plan"><p class="eyebrow">PLANO ATUAL</p><div class="plan-title"><h2>{{s.plan.name}}</h2><strong>{{s.plan.price|currency:s.plan.currency}}<small>/{{s.plan.interval==='Monthly'?'mês':'ano'}}</small></strong></div><span class="status" [class.completed]="s.status==='Active'">{{statusLabel(s.status)}}</span><p>{{s.status==='Trialing'?'Primeira cobrança em':'Próxima renovação em'}} {{s.periodEndsAt|date:'dd MMM yyyy'}}</p>@if(s.status!=='Active'){<button class="primary" [disabled]="checkingOut()" (click)="checkout()">{{checkingOut()?'Abrindo checkout...':'Assinar com Asaas'}} <span>→</span></button>}@else{<div class="active-note">✓ Assinatura ativa e acesso liberado</div>}<small class="secure">Pagamento seguro processado pelo Asaas. O Ordivo não armazena os dados do seu cartão.</small></article><article class="card"><h2>Consumo do plano</h2><div class="usage"><label>Usuários <span>{{s.usersUsed}} / {{s.plan.maxUsers}}</span></label><progress [value]="s.usersUsed" [max]="s.plan.maxUsers"></progress><label>Clientes <span>{{s.customersUsed}} / {{s.plan.maxCustomers}}</span></label><progress [value]="s.customersUsed" [max]="s.plan.maxCustomers"></progress><label>Ordens <span>{{s.serviceOrdersUsed}} / {{s.plan.maxServiceOrders}}</span></label><progress [value]="s.serviceOrdersUsed" [max]="s.plan.maxServiceOrders"></progress></div></article></section>}@else{<div class="loading">Carregando assinatura...</div>}
`,styles:[`.notice{padding:13px 15px;margin-bottom:14px;border-radius:10px;font-size:12px}.notice.success{background:#e5f2ed;color:#286658}.trial-banner{display:flex;justify-content:space-between;align-items:center;padding:18px 20px;margin-bottom:18px;border-radius:12px;background:#fff5cf;border:1px solid #eadb9c;color:#705b13}.trial-banner>div{display:grid;gap:4px}.trial-banner b{font-size:13px}.trial-banner span{font-size:11px}.trial-banner strong{font-size:17px}.trial-banner.urgent{background:#fff0ed;border-color:#edc8c1;color:#973c2f}.current-plan .primary{margin-top:4px}.active-note{padding:12px;margin-top:8px;border-radius:8px;background:#e5f2ed;color:#286658;font-size:12px;font-weight:800}.secure{display:block;margin-top:15px;color:#84908d;line-height:1.5}.alert{margin-bottom:14px}@media(max-width:620px){.trial-banner{align-items:start}.trial-banner strong{font-size:12px}}`]
})
export class TenantBillingComponent{private api=inject(Api);private route=inject(ActivatedRoute);item=signal<Subscription|null>(null);checkingOut=signal(false);error=signal('');message=signal(this.route.snapshot.queryParamMap.get('checkout')==='success'?'Checkout concluído. Aguardando a confirmação do Asaas.':'');daysLeft=computed(()=>{const end=this.item()?.trialEndsAt;if(!end)return 0;return Math.max(0,Math.ceil((new Date(end).getTime()-Date.now())/86400000))});constructor(){this.load()}load(){this.api.subscription().subscribe({next:s=>this.item.set(s),error:e=>this.error.set(errorMessage(e))})}checkout(){if(this.checkingOut())return;this.checkingOut.set(true);this.error.set('');const base=window.location.origin;this.api.post<CheckoutResult>('/api/billing/checkout',{successUrl:`${base}/app/billing?checkout=success`,cancelUrl:`${base}/app/billing?checkout=cancelled`}).pipe(finalize(()=>this.checkingOut.set(false))).subscribe({next:r=>window.location.assign(r.checkoutUrl),error:e=>this.error.set(errorMessage(e))})}statusLabel=(status:string)=>({Trialing:'Período gratuito',Active:'Ativa',PastDue:'Pagamento pendente',Suspended:'Suspensa',Canceled:'Cancelada'} as Record<string,string>)[status]??status}
