import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { finalize } from 'rxjs';
import { Auth } from '../core/auth'; import { errorMessage } from '../core/api';

@Component({ selector:'app-login', imports:[ReactiveFormsModule], changeDetection:ChangeDetectionStrategy.OnPush, template:`
<main class="auth-page">
  <section class="auth-story"><a class="brand"><span>O</span> Ordivo</a><div><p class="eyebrow">OPERAÇÃO, SEM ATRITO</p><h1>Seu serviço.<br><em>No ritmo certo.</em></h1><p class="lead">Clientes, equipe e ordens de serviço em um espaço simples, rápido e confiável.</p></div><div class="story-foot"><span>●</span> Tudo sob controle, de ponta a ponta.</div></section>
  <section class="auth-panel"><form [formGroup]="form" (ngSubmit)="submit()"><div class="mobile-brand brand"><span>O</span> Ordivo</div><p class="eyebrow">BEM-VINDO DE VOLTA</p><h2>Acesse sua conta</h2><p class="muted">Continue de onde parou.</p>
    <label>Email<input type="email" formControlName="email" placeholder="voce@empresa.com" autocomplete="email"></label>
    <label>Senha <a href="#">Esqueci minha senha</a><input type="password" formControlName="password" placeholder="••••••••" autocomplete="current-password"></label>
    @if (error()) { <div class="alert">{{ error() }}</div> }
    <button class="primary wide" [disabled]="form.invalid || loading()">{{ loading() ? 'Entrando...' : 'Entrar' }} <span>→</span></button>
    <p class="signup">Ainda não usa o Ordivo? <a href="/signup">Comece agora</a></p>
  </form></section>
</main>`, styles:[`:host{display:block}.mobile-brand{display:none}.auth-page{min-height:100vh;display:grid;grid-template-columns:1.08fr .92fr}.auth-story{padding:54px 8vw 44px;background:#102a27;color:#fff;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden}.auth-story:after{content:'';position:absolute;width:520px;height:520px;border:1px solid #ffffff14;border-radius:50%;right:-230px;bottom:-170px;box-shadow:0 0 0 80px #ffffff08,0 0 0 160px #ffffff05}.brand{display:flex;align-items:center;gap:12px;font-weight:750;font-size:22px;color:inherit}.brand span{display:grid;place-items:center;width:34px;height:34px;border-radius:10px;background:#e6ff72;color:#17312e;font-family:serif;font-style:italic}.eyebrow{font-size:11px;letter-spacing:.18em;font-weight:800;color:#86a8a3}.auth-story h1{font-size:clamp(48px,5.2vw,76px);line-height:.98;letter-spacing:-.055em;margin:18px 0 28px;max-width:650px}.auth-story h1 em{color:#e6ff72;font-family:Georgia,serif;font-weight:400}.lead{font-size:18px;line-height:1.65;color:#bbcfcc;max-width:500px}.story-foot{font-size:13px;color:#9bb4b0}.story-foot span{color:#e6ff72;margin-right:8px}.auth-panel{display:grid;place-items:center;padding:40px;background:#f7f8f3}.auth-panel form{width:min(420px,100%)}h2{font-size:36px;letter-spacing:-.04em;margin:8px 0}.muted{color:#74817f;margin-bottom:38px}label{font-size:13px;font-weight:700;display:block;margin:20px 0 8px}label a{float:right;font-weight:600;color:#41645f}input{display:block;width:100%;height:52px;border:1px solid #d9dfd9;border-radius:11px;padding:0 15px;margin-top:8px;background:#fff;font:inherit;outline:none}input:focus{border-color:#2d625a;box-shadow:0 0 0 3px #2d625a16}.wide{width:100%;margin-top:18px;justify-content:space-between}.signup{text-align:center;color:#72807d;font-size:13px;margin-top:25px}.signup a{font-weight:800;color:#214c46}.alert{padding:12px 14px;border-radius:10px;background:#fff0ed;color:#a83c2d;font-size:13px}@media(max-width:760px){.auth-page{grid-template-columns:1fr}.auth-story{display:none}.auth-panel{padding:28px;align-items:start;padding-top:14vh}.mobile-brand{display:flex;margin-bottom:54px;color:#17312e}}`]
})
export class LoginComponent { private fb=inject(FormBuilder); private auth=inject(Auth); private router=inject(Router); loading=signal(false); error=signal(''); form=this.fb.nonNullable.group({email:['',[Validators.required,Validators.email]],password:['',Validators.required]}); submit(){if(this.form.invalid)return;this.loading.set(true);this.error.set('');this.auth.login(this.form.getRawValue().email,this.form.getRawValue().password).pipe(finalize(()=>this.loading.set(false))).subscribe({next:()=>this.router.navigateByUrl('/app'),error:e=>this.error.set(errorMessage(e))});} }
