import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { CurrencyPipe, DatePipe } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { Api, errorMessage } from '../core/api';
import { Customer, ServiceOrder, Subscription, Tenant, User } from '../core/models';

@Component({selector:'app-dashboard',imports:[CurrencyPipe,DatePipe],changeDetection:ChangeDetectionStrategy.OnPush,template:`<div class="page-head"><div><p class="eyebrow">VISÃO GERAL</p><h1>Bom dia, vamos organizar o trabalho.</h1><p>Acompanhe os números e o ritmo da sua operação.</p></div><a class="primary" href="/app/orders">+ Nova ordem</a></div>
@if(loading()){<div class="loading">Carregando sua operação...</div>}@else{
<section class="metrics"><article><div class="metric-icon green">▣</div><small>Ordens no total</small><strong>{{orders().length}}</strong><span>Base atual</span></article><article><div class="metric-icon yellow">◷</div><small>Em andamento</small><strong>{{inProgress()}}</strong><span>Exigem atenção</span></article><article><div class="metric-icon blue">♙</div><small>Clientes ativos</small><strong>{{customers().length}}</strong><span>Na carteira</span></article><article><div class="metric-icon purple">R$</div><small>Valor das ordens</small><strong>{{totalValue()|currency:'BRL':'symbol':'1.0-0'}}</strong><span>Volume registrado</span></article></section>
<section class="dashboard-grid"><article class="card"><div class="card-head"><div><h2>Ordens recentes</h2><p>Últimas movimentações da operação</p></div><a href="/app/orders">Ver todas →</a></div><div class="table-wrap"><table><thead><tr><th>ORDEM</th><th>SERVIÇO</th><th>STATUS</th><th>VALOR</th></tr></thead><tbody>@for(o of orders().slice(0,6);track o.id){<tr><td><b>{{o.number}}</b></td><td>{{o.title}}<small>{{o.createdAt|date:'dd MMM, HH:mm'}}</small></td><td><span class="status" [class]="o.status.toLowerCase()">{{label(o.status)}}</span></td><td>{{o.price|currency:'BRL'}}</td></tr>}@empty{<tr><td colspan="4" class="empty">Nenhuma ordem criada ainda.</td></tr>}</tbody></table></div></article>
<aside class="card plan-card"><div class="card-head"><div><h2>Uso do plano</h2><p>{{subscription()?.plan?.name ?? 'Sem assinatura'}}</p></div></div>@if(subscription();as s){<div class="usage"><label>Usuários <span>{{s.usersUsed}} / {{s.plan.maxUsers}}</span></label><progress [value]="s.usersUsed" [max]="s.plan.maxUsers"></progress><label>Clientes <span>{{s.customersUsed}} / {{s.plan.maxCustomers}}</span></label><progress [value]="s.customersUsed" [max]="s.plan.maxCustomers"></progress><label>Ordens no período <span>{{s.serviceOrdersUsed}} / {{s.plan.maxServiceOrders}}</span></label><progress [value]="s.serviceOrdersUsed" [max]="s.plan.maxServiceOrders"></progress></div><div class="trial">{{s.status}} · renova em {{s.periodEndsAt|date:'dd/MM/yyyy'}}</div>}@else{<p class="empty">Assinatura não configurada.</p>}</aside></section>}`})
export class DashboardComponent{private api=inject(Api);loading=signal(true);orders=signal<ServiceOrder[]>([]);customers=signal<Customer[]>([]);subscription=signal<Subscription|null>(null);constructor(){forkJoin({o:this.api.orders(),c:this.api.customers(),s:this.api.subscription()}).subscribe({next:r=>{this.orders.set(r.o.items);this.customers.set(r.c.items);this.subscription.set(r.s);this.loading.set(false)},error:()=>this.loading.set(false)});}inProgress=()=>this.orders().filter(x=>x.status==='Open'||x.status==='InProgress').length;totalValue=()=>this.orders().reduce((n,x)=>n+x.price,0);label=(x:string)=>({Draft:'Rascunho',Open:'Aberta',InProgress:'Em andamento',Completed:'Concluída',Canceled:'Cancelada'}[x]??x);}

@Component({selector:'app-customers',imports:[ReactiveFormsModule,DatePipe],changeDetection:ChangeDetectionStrategy.OnPush,template:`<div class="page-head"><div><p class="eyebrow">RELACIONAMENTO</p><h1>Clientes</h1><p>Organize contatos e histórico de atendimento.</p></div><button class="primary" (click)="showForm.set(!showForm())">+ Novo cliente</button></div>@if(showForm()){<form class="quick-form card" [formGroup]="form" (ngSubmit)="create()"><input formControlName="name" placeholder="Nome"><input formControlName="document" placeholder="CPF/CNPJ"><input formControlName="phone" placeholder="Telefone"><input formControlName="email" placeholder="Email"><button class="primary" [disabled]="form.invalid">Salvar</button></form>}@if(error()){<div class="alert">{{error()}}</div>}<div class="toolbar"><div class="filter">⌕ <input #q placeholder="Buscar por nome" (input)="load(q.value)"></div><span>{{items().length}} clientes</span></div><article class="card table-wrap"><table><thead><tr><th>CLIENTE</th><th>DOCUMENTO</th><th>TELEFONE</th><th>STATUS</th><th>DESDE</th></tr></thead><tbody>@for(c of items();track c.id){<tr><td><div class="name-cell"><span>{{c.name[0]}}</span><div><b>{{c.name}}</b><small>{{c.email||'Sem email'}}</small></div></div></td><td>{{c.document}}</td><td>{{c.phone}}</td><td><span class="status" [class.completed]="c.isActive">{{c.isActive?'Ativo':'Inativo'}}</span></td><td>{{c.createdAt|date:'dd/MM/yyyy'}}</td></tr>}@empty{<tr><td colspan="5" class="empty">Nenhum cliente encontrado.</td></tr>}</tbody></table></article>`})
export class CustomersComponent{private api=inject(Api);private fb=inject(FormBuilder);items=signal<Customer[]>([]);showForm=signal(false);error=signal('');form=this.fb.nonNullable.group({name:['',Validators.required],document:['',Validators.required],phone:['',Validators.required],email:['']});constructor(){this.load()}load(q=''){this.api.customers(q).subscribe({next:x=>this.items.set(x.items),error:e=>this.error.set(errorMessage(e))})}create(){this.api.post<Customer>('/api/customers',this.form.getRawValue()).subscribe({next:()=>{this.form.reset();this.showForm.set(false);this.load()},error:e=>this.error.set(errorMessage(e))})}}

@Component({selector:'app-orders',imports:[ReactiveFormsModule,CurrencyPipe,DatePipe],changeDetection:ChangeDetectionStrategy.OnPush,template:`<div class="page-head"><div><p class="eyebrow">OPERAÇÃO</p><h1>Ordens de serviço</h1><p>Acompanhe cada serviço do início à entrega.</p></div><button class="primary" (click)="showForm.set(!showForm())">+ Nova ordem</button></div>@if(showForm()){<form class="quick-form card order-form" [formGroup]="form" (ngSubmit)="create()"><select formControlName="customerId"><option value="">Selecione o cliente</option>@for(c of customers();track c.id){<option [value]="c.id">{{c.name}}</option>}</select><input formControlName="title" placeholder="Título do serviço"><input formControlName="description" placeholder="Descrição"><input formControlName="price" type="number" placeholder="Valor"><button class="primary" [disabled]="form.invalid">Criar ordem</button></form>}@if(error()){<div class="alert">{{error()}}</div>}<div class="toolbar"><div class="filter">⌕ <input #q placeholder="Número, título ou descrição" (input)="load(q.value)"></div><span>{{items().length}} ordens</span></div><article class="card table-wrap"><table><thead><tr><th>ORDEM</th><th>SERVIÇO</th><th>STATUS</th><th>AGENDAMENTO</th><th>VALOR</th></tr></thead><tbody>@for(o of items();track o.id){<tr><td><b>{{o.number}}</b></td><td>{{o.title}}<small>{{o.description}}</small></td><td><span class="status" [class]="o.status.toLowerCase()">{{label(o.status)}}</span></td><td>{{o.scheduledAt?(o.scheduledAt|date:'dd/MM/yyyy HH:mm'):'Não agendada'}}</td><td><b>{{o.price|currency:'BRL'}}</b></td></tr>}@empty{<tr><td colspan="5" class="empty">Nenhuma ordem encontrada.</td></tr>}</tbody></table></article>`})
export class OrdersComponent{private api=inject(Api);private fb=inject(FormBuilder);items=signal<ServiceOrder[]>([]);customers=signal<Customer[]>([]);showForm=signal(false);error=signal('');form=this.fb.nonNullable.group({customerId:['',Validators.required],title:['',Validators.required],description:['',Validators.required],price:[0,[Validators.required,Validators.min(0)]]});constructor(){this.load();this.api.customers().subscribe(x=>this.customers.set(x.items))}load(q=''){this.api.orders(q).subscribe({next:x=>this.items.set(x.items),error:e=>this.error.set(errorMessage(e))})}create(){this.api.post<ServiceOrder>('/api/service-orders',this.form.getRawValue()).subscribe({next:()=>{this.form.reset({price:0,customerId:'',title:'',description:''});this.showForm.set(false);this.load()},error:e=>this.error.set(errorMessage(e))})}label=(x:string)=>({Draft:'Rascunho',Open:'Aberta',InProgress:'Em andamento',Completed:'Concluída',Canceled:'Cancelada'}[x]??x)}

@Component({selector:'app-users',imports:[DatePipe],changeDetection:ChangeDetectionStrategy.OnPush,template:`<div class="page-head"><div><p class="eyebrow">EQUIPE</p><h1>Usuários</h1><p>Pessoas com acesso ao seu espaço de trabalho.</p></div><button class="primary">+ Convidar usuário</button></div><article class="card table-wrap"><table><thead><tr><th>USUÁRIO</th><th>PAPEL</th><th>EMAIL VERIFICADO</th><th>STATUS</th><th>CRIADO EM</th></tr></thead><tbody>@for(u of items();track u.id){<tr><td><div class="name-cell"><span>{{u.name[0]}}</span><div><b>{{u.name}}</b><small>{{u.email}}</small></div></div></td><td>{{u.role}}</td><td>{{u.isEmailVerified?'Sim':'Pendente'}}</td><td><span class="status" [class.completed]="u.isActive">{{u.isActive?'Ativo':'Inativo'}}</span></td><td>{{u.createdAt|date:'dd/MM/yyyy'}}</td></tr>}</tbody></table></article>`})
export class UsersComponent{private api=inject(Api);items=signal<User[]>([]);constructor(){this.api.users().subscribe(x=>this.items.set(x))}}

@Component({selector:'app-billing',imports:[CurrencyPipe,DatePipe],changeDetection:ChangeDetectionStrategy.OnPush,template:`<div class="page-head"><div><p class="eyebrow">ASSINATURA</p><h1>Plano e cobrança</h1><p>Gerencie capacidade, ciclo e pagamentos.</p></div></div>@if(item();as s){<section class="billing-grid"><article class="card current-plan"><p class="eyebrow">PLANO ATUAL</p><div class="plan-title"><h2>{{s.plan.name}}</h2><strong>{{s.plan.price|currency:s.plan.currency}}<small>/{{s.plan.interval==='Monthly'?'mês':'ano'}}</small></strong></div><span class="status completed">{{s.status}}</span><p>Próxima renovação em {{s.periodEndsAt|date:'dd MMM yyyy'}}</p><button class="primary">Alterar plano</button></article><article class="card"><h2>Consumo</h2><div class="usage"><label>Usuários <span>{{s.usersUsed}} / {{s.plan.maxUsers}}</span></label><progress [value]="s.usersUsed" [max]="s.plan.maxUsers"></progress><label>Clientes <span>{{s.customersUsed}} / {{s.plan.maxCustomers}}</span></label><progress [value]="s.customersUsed" [max]="s.plan.maxCustomers"></progress><label>Ordens <span>{{s.serviceOrdersUsed}} / {{s.plan.maxServiceOrders}}</span></label><progress [value]="s.serviceOrdersUsed" [max]="s.plan.maxServiceOrders"></progress></div></article></section>}@else{<div class="loading">Carregando assinatura...</div>}`})
export class BillingComponent{private api=inject(Api);item=signal<Subscription|null>(null);constructor(){this.api.subscription().subscribe(x=>this.item.set(x))}}

@Component({selector:'app-settings',imports:[ReactiveFormsModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`<div class="page-head"><div><p class="eyebrow">CONFIGURAÇÕES</p><h1>Empresa</h1><p>Dados básicos do seu espaço de trabalho.</p></div></div><form class="card settings-form" [formGroup]="form" (ngSubmit)="save()"><label>Nome da empresa<input formControlName="name"></label><label>Identificador<input formControlName="slug" readonly></label><button class="primary" [disabled]="form.controls.name.invalid">Salvar alterações</button>@if(saved()){<span class="success">Alterações salvas.</span>}</form>`})
export class SettingsComponent{private api=inject(Api);private fb=inject(FormBuilder);saved=signal(false);form=this.fb.nonNullable.group({name:['',Validators.required],slug:['']});constructor(){this.api.tenant().subscribe(x=>this.form.setValue({name:x.name,slug:x.slug}))}save(){this.api.put<Tenant>('/api/tenant',{name:this.form.controls.name.value}).subscribe(x=>{this.form.setValue({name:x.name,slug:x.slug});this.saved.set(true)})}}
