import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { CurrencyPipe } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize } from 'rxjs';
import { Api, errorMessage } from '../core/api';
import { Plan } from '../core/models';

interface Registration { userId:string; tenantId:string; email:string; emailVerificationRequired:boolean; }

@Component({
  selector:'app-signup', imports:[ReactiveFormsModule,CurrencyPipe], changeDetection:ChangeDetectionStrategy.OnPush,
  template:`<main class="signup-page"><header><a class="brand" href="/login"><span>O</span> Ordivo</a><a href="/login">Já tenho uma conta</a></header><section class="intro"><p class="eyebrow">COMECE AGORA</p><h1>Organize sua operação<br>desde o primeiro serviço.</h1><p>Crie sua empresa, escolha o plano e experimente o Ordivo.</p></section>@if(done()){<section class="done card"><div class="mail">✉</div><h2>Confirme seu e-mail</h2><p>Enviamos um link de confirmação para <b>{{registeredEmail()}}</b>. Depois de confirmar, você poderá entrar com a senha que acabou de criar.</p><a class="primary" href="/login">Ir para o login</a></section>}@else{<form class="signup-card card" [formGroup]="form" (ngSubmit)="submit()"><h2>Crie sua conta</h2><div class="fields"><label class="wide">Nome da empresa<input formControlName="tenantName" placeholder="Minha empresa"></label><label>Seu nome<input formControlName="name" autocomplete="name" placeholder="Nome completo"></label><label>E-mail<input type="email" formControlName="email" autocomplete="email" placeholder="voce@empresa.com"></label><label>Senha<input type="password" formControlName="password" autocomplete="new-password" placeholder="Mínimo de 8 caracteres"></label><label>Confirmar senha<input type="password" formControlName="confirmation" autocomplete="new-password" placeholder="Digite novamente"></label></div><h3>Escolha seu plano</h3>@if(loadingPlans()){<p class="muted">Carregando planos...</p>}@else{<div class="plans">@for(plan of plans();track plan.id){<label class="plan" [class.selected]="form.controls.planId.value===plan.id"><input type="radio" formControlName="planId" [value]="plan.id"><div><b>{{plan.name}}</b><small>{{plan.trialDays>0?plan.trialDays+' dias grátis':'Acesso imediato'}}</small></div><strong>{{plan.price|currency:plan.currency}}<small>/{{plan.interval==='Monthly'?'mês':'ano'}}</small></strong><p>{{plan.maxUsers}} usuários · {{plan.maxCustomers}} clientes · {{plan.maxServiceOrders}} OS</p></label>}@empty{<div class="alert">Nenhum plano disponível no momento.</div>}</div>}@if(mismatch()){<div class="alert">As senhas não são iguais.</div>}@if(error()){<div class="alert">{{error()}}</div>}<button class="primary submit" [disabled]="form.invalid||mismatch()||sending()">{{sending()?'Criando sua conta...':'Criar conta e iniciar trial'}} <span>→</span></button><p class="terms">Ao continuar, você concorda com os termos de uso do Ordivo.</p></form>}</main>`,
  styles:[`:host{display:block}.signup-page{min-height:100vh;padding:30px max(24px,7vw) 60px;background:#f4f6f1;color:#18322f}header{display:flex;align-items:center;justify-content:space-between;margin-bottom:55px}header>a:last-child{font-size:12px;font-weight:800;color:#315c55}.brand{display:flex;align-items:center;gap:11px;font-size:21px;font-weight:800}.brand span{display:grid;place-items:center;width:34px;height:34px;border-radius:10px;background:#173f39;color:#e6ff72;font-family:Georgia,serif;font-style:italic}.intro{text-align:center;margin:0 auto 28px}.intro h1{font-size:clamp(34px,4vw,54px);line-height:1.02;letter-spacing:-.05em;margin:10px 0 15px}.intro>p:last-child{color:#74817f}.signup-card,.done{width:min(720px,100%);margin:auto;padding:30px}.signup-card h2{margin:0 0 22px;font-size:22px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:15px}.wide{grid-column:1/-1}label{font-size:11px;font-weight:800}input:not([type=radio]){display:block;width:100%;height:46px;margin-top:6px;padding:0 13px;border:1px solid #d8e0d9;border-radius:9px;font:inherit;outline:none}input:focus{border-color:#2d625a;box-shadow:0 0 0 3px #2d625a16}h3{font-size:13px;margin:25px 0 10px}.plans{display:grid;gap:9px}.plan{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:12px;padding:14px;border:1px solid #dce3dc;border-radius:10px;cursor:pointer}.plan.selected{border-color:#2d625a;background:#f1f7f3;box-shadow:0 0 0 2px #2d625a12}.plan input{accent-color:#173f39}.plan div small,.plan strong small{display:block;color:#7c8986;font-size:10px;margin-top:3px}.plan strong{text-align:right}.plan p{grid-column:2/-1;margin:0;color:#7c8986;font-size:10px}.submit{width:100%;margin-top:20px;justify-content:space-between}.terms{text-align:center;color:#8a9693;font-size:10px;margin:14px 0 0}.alert{padding:11px 13px;margin-top:13px;border-radius:9px;background:#fff0ed;color:#a83c2d;font-size:12px}.muted{color:#74817f}.done{text-align:center}.mail{display:grid;place-items:center;width:58px;height:58px;margin:auto;border-radius:50%;background:#e5f2ed;color:#286658;font-size:25px}.done h2{font-size:28px}.done p{color:#64736f;line-height:1.6}.done .primary{display:inline-flex;margin-top:12px}@media(max-width:620px){.signup-page{padding:24px 18px 45px}header{margin-bottom:38px}.signup-card{padding:21px}.fields{grid-template-columns:1fr}.wide{grid-column:auto}.plan{grid-template-columns:auto 1fr}.plan>strong{grid-column:2;text-align:left}.plan p{grid-column:2}}`]
})
export class SignupComponent{
  private api=inject(Api);private fb=inject(FormBuilder);plans=signal<Plan[]>([]);loadingPlans=signal(true);sending=signal(false);done=signal(false);error=signal('');registeredEmail=signal('');
  form=this.fb.nonNullable.group({planId:['',Validators.required],tenantName:['',[Validators.required,Validators.maxLength(200)]],name:['',[Validators.required,Validators.maxLength(120)]],email:['',[Validators.required,Validators.email,Validators.maxLength(254)]],password:['',[Validators.required,Validators.minLength(8),Validators.maxLength(128)]],confirmation:['',Validators.required]});
  constructor(){this.api.get<Plan[]>('/api/plans').pipe(finalize(()=>this.loadingPlans.set(false))).subscribe({next:plans=>{this.plans.set(plans);if(plans.length===1)this.form.controls.planId.setValue(plans[0].id)},error:error=>this.error.set(errorMessage(error))})}
  mismatch=()=>this.form.controls.confirmation.dirty&&this.form.controls.password.value!==this.form.controls.confirmation.value;
  submit(){if(this.form.invalid||this.mismatch()||this.sending())return;this.sending.set(true);this.error.set('');const {confirmation,...payload}=this.form.getRawValue();this.api.post<Registration>('/api/auth/register',payload).pipe(finalize(()=>this.sending.set(false))).subscribe({next:r=>{this.registeredEmail.set(r.email);this.done.set(true)},error:error=>this.error.set(errorMessage(error))})}
}
